In [1]:
# 1. Sử dụng array và matrix trong numpy
# 1.1. Thông tin tóm gọn
import numpy as np

# Tạo mảng D và E
D = np.array([[1, 2], [3, 4]])
E = np.array([[1, 2], [3, 5]])

# In ra mảng E trước khi sao chép
print("Mảng E trước khi sao chép:")
print(E)

# Sao chép giá trị từ D vào E
np.copyto(E, D)

# In ra mảng E sau khi sao chép
print("\nMảng E sau khi sao chép từ D:")
print(E)


Mảng E trước khi sao chép:
[[1 2]
 [3 5]]

Mảng E sau khi sao chép từ D:
[[1 2]
 [3 4]]


In [3]:
import numpy as np

# Tạo ma trận 2D với numpy.matrix
B = np.matrix("[1 2 3; 4 5 6]")
print("Ma trận B:")
print(B)

# Sử dụng các hàm đặc biệt .H, .I, và .A
print("\nChuyển vị của B (B.H):")
print(B.H)

print("\nNghịch đảo của B (B.I):")
print(B.I)

print("\nChuyển ma trận B thành array (B.A):")
print(B.A)

# Tạo một ma trận chứa các phần tử không phải số
x = np.array([['a', 'b'], ['c', 'd']])
y = 'x'
C = np.matrix([[x[0, 0], x[0, 1]], [y, 1]])  # Đảm bảo mọi phần tử là chuỗi

print("\nMa trận C chứa các phần tử không phải số:")
print(C)

# Kiểm tra việc sử dụng numpy.matrix với ma trận 3D (sẽ gây lỗi)
try:
    A = np.matrix([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Lỗi khi tạo ma trận 3D
except Exception as e:
    print("\nLỗi khi sử dụng numpy.matrix với ma trận 3D:")
    print(e)

# Sử dụng numpy.array với ma trận 3D (hoạt động bình thường)
A = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Tạo ma trận 3D với numpy.array
print("\nMa trận 3D với numpy.array:")
print(A)


Ma trận B:
[[1 2 3]
 [4 5 6]]

Chuyển vị của B (B.H):
[[1 4]
 [2 5]
 [3 6]]

Nghịch đảo của B (B.I):
[[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]

Chuyển ma trận B thành array (B.A):
[[1 2 3]
 [4 5 6]]

Ma trận C chứa các phần tử không phải số:
[['a' 'b']
 ['x' '1']]

Lỗi khi sử dụng numpy.matrix với ma trận 3D:
matrix must be 2-dimensional

Ma trận 3D với numpy.array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# 1.3. Đối tượng matrix từ các hàm trong gói numpy.matlib 
import numpy as np
from numpy import matlib

# Tạo ma trận đơn vị 5x5
G = matlib.identity(5)
print("Ma trận đơn vị 5x5 (G):")
print(G)

# Tạo ma trận ngẫu nhiên có kích thước 3x2
H = matlib.randn(3, 2)
print("\nMa trận ngẫu nhiên 3x2 (H):")
print(H)

# Tạo ma trận toàn 0 với kích thước 4x4
K = matlib.zeros([4, 4])
print("\nMa trận toàn 0 kích thước 4x4 (K):")
print(K)

# Tạo ma trận toàn 1 với kích thước 3x3
L = matlib.ones([3, 3])
print("\nMa trận toàn 1 kích thước 3x3 (L):")
print(L)

# Tạo ma trận bằng cách sử dụng lệnh `repmat` để lặp lại một ma trận
A = np.array([[1, 2], [3, 4]])  # Ma trận 2x2
B = matlib.repmat(A, 2, 3)  # Lặp lại ma trận A 2 lần theo chiều dọc, 3 lần theo chiều ngang
print("\nMa trận lặp lại A 2x3 lần (B):")
print(B)


Ma trận đơn vị 5x5 (G):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Ma trận ngẫu nhiên 3x2 (H):
[[-1.64872847  1.22416156]
 [-0.02824347 -0.7994618 ]
 [ 0.69265929 -0.10542682]]

Ma trận toàn 0 kích thước 4x4 (K):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ma trận toàn 1 kích thước 3x3 (L):
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Ma trận lặp lại A 2x3 lần (B):
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [5]:
# 2 Ứng dụng 2 –Liên phân số và số 
# 2.1. Liên phân số
#2.2. Liên phân số biểu diễn số 
import numpy as np

# Dãy số c (thử chạy với dãy c dài khác nhau)
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]  # có thể thay đổi dãy số c

# Khởi tạo ma trận 2x2
M = np.mat([[1, 2], [3, 4]])

# Thực hiện tính toán liên phân số với dãy c
for i in range(len(c)):
    # Tạo ma trận 2x2
    ci = np.mat([[1, 1], [1, 0]])
    
    # Cập nhật phần tử đầu tiên của ma trận
    ci[0, 0] = c[i]
    
    # Nếu là lần đầu tiên, gán ma trận M bằng ma trận ci
    if i == 0:
        M = ci
    else:
        # Nếu không, nhân ma trận M với ma trận ci
        M = M.dot(ci)

# In kết quả ma trận cuối cùng
print("Ma trận cuối cùng M:")
print(M)

# Tính giá trị Pi từ dãy liên phân số và in ra kết quả
pi_approximation = M[0, 0] / M[1, 0]
print("\nGiá trị xấp xỉ của Pi:")
print(pi_approximation)


Ma trận cuối cùng M:
[[165707065  80143857]
 [ 52746197  25510582]]

Giá trị xấp xỉ của Pi:
3.1415926535897936


In [6]:
# 3.2. Phương pháp bình phương cực tiểu (mô hình tuyến tính) 
import numpy as np

# Nhập dữ liệu X và Y
X = np.array([[1, 1],
              [1, 2],
              [1, 3],
              [1, 4],
              [1, 5]])
Y = np.array([1, 2, 4, 4, 6])

# Tính X^T
XT = X.T
print("Ma trận X^T:")
print(XT)

# Tính A1 = (X^T X)^(-1) và A2 = X^T Y
A1 = np.linalg.inv(np.dot(XT, X))
A2 = np.dot(XT, Y)

# Tính A = A1 . A2
A = np.dot(A1, A2)
print("\nVector tham số A:")
print(A)

# Suy ra phương trình đường thẳng
a0, a1 = A
print(f"\nPhương trình đường thẳng gần đúng nhất: y = {a0:.1f} + {a1:.1f}x")

# Tính các giá trị f(x_i)
f = a0 + a1 * np.array([1, 2, 3, 4, 5])
print("\nCác giá trị f(x_i):")
print(f)

# Tính sai số tổng bình phương
errors = Y - f
squared_errors = errors**2
total_squared_error = np.sum(squared_errors)
print("\nSai số tổng bình phương:")
print(f"{total_squared_error:.1f}")

# Dự đoán chiều cao ngày thứ 6
x6 = 6
y6 = a0 + a1 * x6
print(f"\nDự đoán chiều cao ngày thứ 6: {y6:.1f} cm")

# So sánh với mô hình của Linh và Loan
print("\nSo sánh với mô hình của Linh và Loan:")
# Mô hình của Linh: f(x) = 0.5 + x
f_linh = 0.5 + np.array([1, 2, 3, 4, 5])
squared_errors_linh = (Y - f_linh)**2
total_squared_error_linh = np.sum(squared_errors_linh)
print(f"Sai số tổng bình phương của Linh (f(x) = 0.5 + x): {total_squared_error_linh:.2f}")

# Mô hình của Loan: f(x) = 1.2x
f_loan = 1.2 * np.array([1, 2, 3, 4, 5])
squared_errors_loan = (Y - f_loan)**2
total_squared_error_loan = np.sum(squared_errors_loan)
print(f"Sai số tổng bình phương của Loan (f(x) = 1.2x): {total_squared_error_loan:.2f}")

Ma trận X^T:
[[1 1 1 1 1]
 [1 2 3 4 5]]

Vector tham số A:
[-0.2  1.2]

Phương trình đường thẳng gần đúng nhất: y = -0.2 + 1.2x

Các giá trị f(x_i):
[1.  2.2 3.4 4.6 5.8]

Sai số tổng bình phương:
0.8

Dự đoán chiều cao ngày thứ 6: 7.0 cm

So sánh với mô hình của Linh và Loan:
Sai số tổng bình phương của Linh (f(x) = 0.5 + x): 1.25
Sai số tổng bình phương của Loan (f(x) = 1.2x): 1.00


In [7]:
######### BÀI TẬP CHƯƠNG ##################
# Câu 1:
import numpy as np

def bpcuctieu(a):
    n = len(a)
    o1 = [1.0] * n 
    b = [float(i) for i in range(n)] 
    X = np.array([o1, b]).T 
    Y = np.array(a)
    XT = X.T
    u = np.dot(XT, X) 
    u_inv = np.linalg.inv(u) 
    v = np.dot(u_inv, XT) 
    A = np.dot(v, Y) 
    return A

# Chạy thử với dữ liệu
dulieu = [10.0, 8, 7, 5, 2]
A = bpcuctieu(dulieu)
a0, a1 = A
print(f"Phương trình tuyến tính: y = {a0:.1f} {a1:+.1f}x")

# Tính sai số tổng bình phương
x = np.array([0, 1, 2, 3, 4])
y = np.array(dulieu)
f = a0 + a1 * x
errors = y - f
total_squared_error = np.sum(errors**2)
print(f"Sai số tổng bình phương: {total_squared_error:.2f}")

# Dự đoán lượng thuốc sau 5 giờ
x5 = 5
y5 = a0 + a1 * x5
print(f"Dự đoán lượng thuốc sau 5 giờ: {y5:.1f} đơn vị")

Phương trình tuyến tính: y = 10.2 -1.9x
Sai số tổng bình phương: 1.10
Dự đoán lượng thuốc sau 5 giờ: 0.7 đơn vị
