In [6]:
# 1. Định thức và các tính chất

import numpy as np

n = 4
X = np.array(range(1, n + 1))
sigma = np.array([4, 3, 2, 1])

def sgn_by_def(sigma):
    ket_qua = 1.0
    for i in range(len(X) - 1):
        for j in range(i + 1, len(X)):
            ket_qua = ket_qua * ((X[i] - X[j]) / (sigma[i] - sigma[j]))
    return int(ket_qua)

sigma = np.array([2, 1, 3, 4])
print(sgn_by_def(sigma))

sigma = np.array([4, 3, 2, 1])
print(sgn_by_def(sigma))

sigma = np.array([1, 2, 3, 4])
print(sgn_by_def(sigma))


-1
1
1


In [7]:
# Sinh viên thực hành đoạn mã minh họa tính toán định thức của một ma trận theo định nghĩa. 
import numpy as np
from itertools import permutations
import math

def sgn_by_def(sigma):
    ket_qua = 1.0
    for i in range(len(sigma) - 1):
        for j in range(i + 1, len(sigma)):
            ket_qua = ket_qua * ((i + 1 - (j + 1)) / (sigma[i] - sigma[j]))
    return int(ket_qua)


n = 3
X = []
for i in range(1, n + 1):
    X.append(i)
Sn = list(permutations(X))  # tạo hoán vị của tập
print("Tập hoán vị Sn:", Sn)

det = 0 


def phatsinh_dinhthuc(n):
    X = []
    for i in range(1, n + 1):
        X.append(i)
    Sn = list(permutations(X))
    dinhthuc = ""
    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = ""
        for i in range(1, n + 1):
            sigma[sn.index(i)] = i
            product = product + "a" + str(i) + str(sn.index(i) + 1)
        dau = sgn_by_def(sigma)  # Gọi hàm sgn_by_def
        if (dau != 1):
            product = " - " + product
        else:
            product = " + " + product
        dinhthuc = dinhthuc + product
    return dinhthuc

# Thử nghiệm với n=2 và n=3
print("Công thức định thức cho n=2:", phatsinh_dinhthuc(2)) 
print("Công thức định thức cho n=3:", phatsinh_dinhthuc(3))  


def tinhtoan_dinhthuc(A):
    X = []
    n = len(A)
    for i in range(1, n + 1):
        X.append(i)
    Sn = list(permutations(X))
    det = 0
    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = 1.0
        for i in range(n):
            sigma[sn.index(i + 1)] = i + 1
            product *= A[i][list(sn).index(i + 1)]
        dau = sgn_by_def(sigma)  # Gọi hàm sgn_by_def
        det += dau * product
    return det

# Ví dụ sử dụng với ma trận 2x2
A = np.array([[1, 2], [3, 4]])
print("Định thức của ma trận A:", tinhtoan_dinhthuc(A))  


n = 4
X = np.array(range(1, n + 1))
sigma = np.array([4, 3, 2, 1])
print("Dấu của phép thế sigma:", sgn_by_def(sigma))

sigma = np.array([2, 1, 3, 4])
print("Dấu của phép thế sigma:", sgn_by_def(sigma))

sigma = np.array([1, 2, 3, 4])
print("Dấu của phép thế sigma:", sgn_by_def(sigma))

Tập hoán vị Sn: [(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]
Công thức định thức cho n=2:  + a11a22 - a12a21
Công thức định thức cho n=3:  + a11a22a33 - a11a23a32 - a12a21a33 + a13a21a32 + a12a23a31 - a13a22a31
Định thức của ma trận A: -2.0
Dấu của phép thế sigma: 1
Dấu của phép thế sigma: -1
Dấu của phép thế sigma: 1


In [14]:

# Hệ hai phương trình tuyến tính bậc 1:
import numpy as np
from scipy import linalg  # Lưu ý: Sử dụng linalg từ scipy thay vì numpy.linalg để khớp với tài liệu

# Ma trận hệ số A
A = np.array([[4, -2], [3, -5]])  # Khai báo ma trận A

# Ma trận A1 (thay cột đầu bằng vector kết quả)
A1 = np.array([[10, -2], [11, -5]])  # Khai báo ma trận A1

# Ma trận A2 (thay cột thứ hai bằng vector kết quả)
A2 = np.array([[4, 10], [3, 11]])  # Khai báo ma trận A2

# Tính định thức
detA = linalg.det(A)  # Tính định thức của ma trận A
detA1 = linalg.det(A1)  # Tính định thức của ma trận A1
detA2 = linalg.det(A2)  # Tính định thức của ma trận A2

# In ra các định thức
print(detA, detA1, detA2)

# Kiểm tra và tính nghiệm
if (detA != 0):  # Nếu định thức khác 0
    x1 = detA1 / detA  # Tính x1
    x2 = detA2 / detA  # Tính x2
    print("Hai nghiệm của phương trình là:", x1, x2)  # In ra nghiệm
else:
    print("Hệ phương trình không có nghiệm duy nhất vì định thức = 0")

-14.0 -28.0 14.000000000000004
Hai nghiệm của phương trình là: 2.0 -1.0000000000000002


In [13]:
# Hệ ba phương trình tuyến tính bậc 1:
import numpy as np
from scipy import linalg

# Ma trận hệ số A3
A3 = np.array([[-1, -2, -3], [2, -2, 1], [3, 4, 4]])

# Vector kết quả b
b = np.array([1, 3, 2])

# Ma trận A3_x (thay cột đầu bằng vector b)
A3_x = np.array([[b[0], A3[0][1], A3[0][2]],
                 [b[1], A3[1][1], A3[1][2]],
                 [b[2], A3[2][1], A3[2][2]]])

# Ma trận A3_y (thay cột thứ hai bằng vector b)
A3_y = np.array([[A3[0][0], b[0], A3[0][2]],
                 [A3[1][0], b[1], A3[1][2]],
                 [A3[2][0], b[2], A3[2][2]]])

# Ma trận A3_z (thay cột thứ ba bằng vector b)
A3_z = np.array([[A3[0][0], A3[0][1], b[0]],
                 [A3[1][0], A3[1][1], b[1]],
                 [A3[2][0], A3[2][1], b[2]]])

# Tính định thức
detA3 = linalg.det(A3)
detA3_x = linalg.det(A3_x)
detA3_y = linalg.det(A3_y)
detA3_z = linalg.det(A3_z)

print(f"Định thức A3: {detA3}")
print(f"Định thức A3_x: {detA3_x}")
print(f"Định thức A3_y: {detA3_y}")
print(f"Định thức A3_z: {detA3_z}")

# Tính nghiệm
if detA3 != 0:
    x = detA3_x / detA3
    y = detA3_y / detA3
    z = detA3_z / detA3
    print(f"Nghiệm (x, y, z): {x}, {y}, {z}")
else:
    print("Hệ phương trình không có nghiệm duy nhất vì định thức = 0")

Định thức A3: -20.0
Định thức A3_x: -39.99999999999999
Định thức A3_y: 0.0
Định thức A3_z: 20.0
Nghiệm (x, y, z): 1.9999999999999996, -0.0, -1.0


In [15]:
# 4. Bài toán ứng dụng 1: Tính diện tích đa giác, thể tích và các phương trình đường, mặt.
from sympy import Matrix

# Tính diện tích tam giác của 3 điểm A(1,0), B(4,3), C(2,2)
M = Matrix([[1, 0, 1], [4, 3, 1], [2, 2, 1]])
S = 0.5 * abs(M.det())  # Diện tích là nửa định thức tuyệt đối của ma trận
print(S)

1.50000000000000


In [16]:
########### BÀI TẬP CHƯƠNG 4 ##########
# Câu 1
import numpy as np
from scipy import linalg

# Ma trận A
A = np.array([[4, -2], [3, -5]])

# a. Tính ma trận cofactor (vectơ đường thẳng)
def cofactor_matrix(A):
    n = len(A)
    cofactors = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            minor = np.delete(np.delete(A, i, axis=0), j, axis=1)
            cofactors[i][j] = (-1) ** (i + j) * np.linalg.det(minor)
    return cofactors

cofactor = cofactor_matrix(A)
print("Ma trận cofactor (vectơ đường thẳng):")
print(cofactor)

# b. Tính ma trận lân cận (adjoint matrix)
adj_A = cofactor.T  # Ma trận lân cận là chuyển vị của ma trận cofactor
print("Ma trận lân cận (adjoint matrix):")
print(adj_A)

# Tính định thức
detA = linalg.det(A)
print("Định thức của A:", detA)

# Tính ma trận nghịch đảo nếu có
if detA != 0:
    inv_A = (1 / detA) * adj_A
    print("Ma trận nghịch đảo A^-1:")
    print(inv_A)
else:
    print("Ma trận không khả nghịch vì định thức = 0")

Ma trận cofactor (vectơ đường thẳng):
[[-5. -3.]
 [ 2.  4.]]
Ma trận lân cận (adjoint matrix):
[[-5.  2.]
 [-3.  4.]]
Định thức của A: -14.0
Ma trận nghịch đảo A^-1:
[[ 0.35714286 -0.14285714]
 [ 0.21428571 -0.28571429]]


In [18]:
# Câu 2
import sympy as sp

# Khai báo biến
x, y = sp.symbols('x y')
x1, y1 = 1, 2
x2, y2 = 4, 6
x3, y3 = 5, 1

# Tạo ma trận định thức
M = sp.Matrix([
    [x**2 + y**2, x, y, 1],
    [x1**2 + y1**2, x1, y1, 1],
    [x2**2 + y2**2, x2, y2, 1],
    [x3**2 + y3**2, x3, y3, 1],
])

# Tính định thức
circle_eq = M.det()

# Hiển thị phương trình đường tròn
sp.pprint(circle_eq)
print("Phương trình đường tròn là:")
print(sp.simplify(circle_eq))


      2               2              
- 19⋅x  + 131⋅x - 19⋅y  + 125⋅y - 286
Phương trình đường tròn là:
-19*x**2 + 131*x - 19*y**2 + 125*y - 286
